### ISSUE TITLE
load balancer internal creation failed

### ISSUE THREAD

**Issue by albundy83** [outscale/cloud-provider-osc#350]
**What happened**:
Hello,

using the following template:
 ```yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana-lb-internal
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
  annotations:
    service.beta.kubernetes.io/osc-load-balancer-name: grafana-internal
    service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
```

I did not succeed to create an internal load balancer.
Here the error message from osc:
```
I0606 10:02:59.881882       1 log_handler.go:35] AWS API Send: elasticloadbalancing CreateLoadBalancer &{CreateLoadBalancer POST / <nil> <nil>} {
  AvailabilityZones: ["eu-west-2a"],
  Listeners: [{
      InstancePort: 30020,
      InstanceProtocol: "TCP",
      LoadBalancerPort: 3000,
      Protocol: "TCP"
    }],
  LoadBalancerName: "grafana-internal",
  Scheme: "internal",
  Tags: [{
      Key: "kubernetes.io/service-name",
      Value: "monitoring/grafana-lb-internal"
    },{
      Key: "OscK8sClusterID/kube",
      Value: "owned"
    }]
}
I0606 10:02:59.881926       1 log_handler.go:40] AWS API ValidateResponse: elasticloadbalancing CreateLoadBalancer &{CreateLoadBalancer POST / <nil> <nil>} {
  AvailabilityZones: ["eu-west-2a"],
  Listeners: [{
      InstancePort: 30020,
      InstanceProtocol: "TCP",
      LoadBalancerPort: 3000,
      Protocol: "TCP"
    }],
  LoadBalancerName: "grafana-internal",
  Scheme: "internal",
  Tags: [{
      Key: "kubernetes.io/service-name",
      Value: "monitoring/grafana-lb-internal"
    },{
      Key: "OscK8sClusterID/kube",
      Value: "owned"
    }]
} 400 Bad Request
2024/06/06 10:02:59 DEBUG: Response elasticloadbalancing/CreateLoadBalancer Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Content-Length: 371
Connection: keep-alive
I0606 10:02:59.882102       1 controller.go:880] Finished syncing service "monitoring/grafana-lb-internal" (661.264072ms)
Content-Type: text/xml;charset=UTF-8
E0606 10:02:59.882114       1 controller.go:320] error processing service monitoring/grafana-lb-internal (will retry): failed to ensure load balancer: InvalidScheme: The value specified for scheme is invalid. You can only specify a scheme for load balancer in VPC
Date: Thu, 06 Jun 2024 10:02:59 GMT
Server: nginx
	status code: 400, request id: 
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.12", GitCommit:"12031002905c0410706974560cbdf2dad9278919", GitTreeState:"clean", BuildDate:"2024-03-15T02:15:31Z", GoVersion:"go1.21.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.14+rke2r1", GitCommit:"f678fbc2f5af87ec6552b7ac6ebbe26258b0d120", GitTreeState:"clean", BuildDate:"2024-05-15T15:42:29Z", GoVersion:"go1.21.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
We use Cloud Provider OSC versions:
```
ccm_version       = "v0.2.3"
ccm_helm_version  = "0.3.0"
```

- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-10-0-0-10 6.1.0-13-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
```
- Install tools:
- Others:

/kind bug
